# Generated by Django 5.1.1 on 2024-09-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_author_created_at_author_gender_book_pages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateTimeField(),
        ),
    ]
