# Generated by Django 5.1.1 on 2024-09-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AddField(
            model_name="book",
            name="title",
            field=models.CharField(default="none", max_length=100),
            preserve_default=False,
        ),
    ]
